# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 config.vm.synced_folder ".", "/vagrant", disabled: true

 config.vm.define "ansible" do |ansible|
    ansible.vm.box = "sbeliakou/centos-7.3-x86_64-minimal"
    ansible.vm.network "private_network", ip: "192.168.56.10"
    ansible.vm.hostname = "ansible"
    ansible.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
    ansible.vm.network :forwarded_port, guest: 8080, host: 8090, auto_correct: true
    ansible.vm.provider "virtualbox" do |v|
	v.memory = "2048"
	v.name = "ansible"
    end
  end
end
